### ISSUE TITLE
Dodrio mistaken for Doduo

### ISSUE THREAD

**Issue by WillyReyno** [farkam135/GoIV#155]
Hi and thank you for this excellent app! 

Similar to the Nidoran detection, everytime I try getting the IV of a Dodrio the app detects a Doduo. 

I'm using a LG Nexus 5 with GoIV 2.1.0

**Comment by Blaisorblade** [comment]
Can you try again with 2.2.0? There were *lots* of changes to this code and the OCR is tricky—changelog here: https://github.com/farkam135/GoIV/releases. At least the Nidorans are fixed :-)

**Comment by WillyReyno** [comment]
Just updated but the problem remains : 
![screenshot_20160823-205647](https://cloud.githubusercontent.com/assets/5576482/17905750/7d7891b2-6974-11e6-96b4-5e91db4c517d.png)

**Comment by Eccenux** [comment]
Yellow color indicates there was no perfect (green would mean the match is perfect). So probably OCR problem.

@WillyReyno Note that in GoIV 2.2 if you click on the name you should see Dotrio as a second option on the list.

**Comment by farkam135** [comment]
Closing due to being an OCR issue. OCR is something that is constantly being worked on and improved. Some devices will always have issues identifying certain pokemon.
