### ISSUE TITLE
Can't scan CP on 2000 CP Vaporeon

### ISSUE THREAD

**Issue by Nizzem** [farkam135/GoIV#297]
Tried to scan this Vaporeon on my Oneplus One phone, trainer level 25. CP always showed as 10. I was able to scan CP on the previous level and the level after this.

![screenshot_20160829-222325](https://cloud.githubusercontent.com/assets/20824577/18074610/e1b45a46-6e3b-11e6-9b92-a776a42679a5.png)

**Comment by SteinerKD** [comment]
This happened to me as well with a 2021 Gyarados. First time it showed correctly, then I clicked the top stat for it after which it said there was no combinations for it and CP was locked as 10.
After viewing another Pokémon and going back it showed correctly again (I have not been able to reproduce this though).

**Comment by Blaisorblade** [comment]
@SteinerKD the CP shouldn't be locked—the OCR can totally screw up but it should always be possible to edit it by hand (and if not, that's a bug I'm sure we can fix).

This other thread misreads a CP 200 pokemon (not clear if only that). I'm not convinced there's a relation but I'm watching for it.
https://www.reddit.com/r/GoIV/comments/50ex8f/bug/

**Comment by SteinerKD** [comment]
In my case I couldn't edit the 10cp showing, but maybe I did something wrong and as I can't reproduce the error I can't verify that statement. If I ever get it to happen again I will try more things and try to document it somehow.

**Comment by rpgrca** [comment]
I can confirm I can't OCR a 200CP Pidgey, it always goes to 10CP. It would look as if the OCR reader can't just detect the "200" combination correctly.

**Comment by Blaisorblade** [comment]
@rpgrca Thanks a lot! We just need to replace Z with 2 when we expect numbers, which we already do elsewhere (copy-paste *is* bad). I've pushed to master a fix doing this, and it fixes the problem on my CP200 Seel (hadn't noticed I had one)—do you want to give it a try?

**Comment by rpgrca** [comment]
Yep, it work, thanks.

**Comment by SteinerKD** [comment]
Still happening for me with 2021 Gayrados (says 10cp) and 1380 Kingler (says 1cp).
Both have their IV % in their name, might that affect things? (GoIV 3.1.0)

**Comment by rpgrca** [comment]
@SteinerKD  Kingler is probably because he waves his pincer and might block the CP value, it happens with Gastly, Weezing and others that do that too. Try to press the button when he lowers it. Recognizing 1 means the OCR only saw the 1, while recognizing 10 probably means there was an error (like mistaking numbers with letters). No idea about gyarados, I don't have one.

**Comment by Blaisorblade** [comment]
@rpgrca's reply is correct, and I can confirm the CP scanning is independent from the name.
