### ISSUE TITLE
Force close after pressing start with 39+ trainer level.

### ISSUE THREAD

**Issue by topcatzero** [farkam135/GoIV#343]
Using GoIV 3.0.1 offline. If it helps to narrow it down, this seems to occur before any attempt to start POGO. Level 39 and 40 both cause this. With a trainer level of 41 I get a toast saying it's invalid, as expected.

Nexus 5X Android 7.0

**Comment by Blaisorblade** [comment]
Thanks for the report! I know at least two reasons 3.0.1 would crash at those levels, and those were fixed in 3.1.0 and would *probably* be at startup. (We're fixing up the APK for packaging issues).

Meanwhile, do you happen to know what's the maximum pokemon level for trainers with such levels? It's normally trainerLevel + 1.5. We haven't found enough info and this may impact level calculations. Screenshots like the ones in https://github.com/farkam135/GoIV/issues/301 might help.

**Comment by rpgrca** [comment]
> Thanks for the report! I know at least two reasons 3.0.1 would crash at those levels, and those were fixed in 3.1.0 and would probably be at startup. (We're fixing up the APK for packaging issues).
Chiming in. No time to test the latest code, but have maybe 2 or 3 days-old one, and it crashed too.

**Comment by topcatzero** [comment]
Great updates! I really like the direction this project is going. I just tried 3.1.0. Unfortunately this force close still occurs. Sorry I'm using the offline version. I really appreciate that you offer it though!

I don't know much about max pokemon levels. #301 is the first I've heard of any divergence from the trainer level + 1.5 rule. I can't provide any info about it, my account is not anywhere near level 39. I discovered this issue while trying to use GoIV to analyze a screenshot on Reddit. I didn't know their trainer level, so I went with 40 and figured I would manually adjust the arc until stats could be calculated. m.reddit.com/r/pokemongodev/comments/50qpyq/ivs_of_my_dragonite_cannot_be_calculated <-- probably a POGO bug.

Side note: you guys probably didn't envision this kind of use. I imagine this would mess with OCR learning and require me to clear data afterwards. Especially if the screenshot came from a device with different screen dimensions.

**Comment by Blaisorblade** [comment]
First, I just reproduced the bug at the first attempt. Finding the offending code should be easy as soon as I get access to a debugger (I'm on the wrong computer).

As a side note, that pokemon has level around 7 (they seem to say, haven't read the full thread) so given the arc position I'd guess you can start from lower levels (which I guess you did), while we fix this. Thanks anyway for the report!

> Side note: you guys probably didn't envision this kind of use.

We surely envision lvl 40 users some day, we're just not ready yet!

Not really, but it probably kind of works, as long as the screenshot is displayed in full screen—you might find other bugs though.

It would be nice to support that better (though it's not a priority)—I'd love having a testsuite made of screenshots for integration testing.

> I imagine this would mess with OCR learning and require me to clear data afterwards. Especially if the screenshot came from a device with different screen dimensions.

No no, we just learn mappings from OCRed names to pokemon names, nothing that fancy. If you name a pokemon 77.8 AEO, at worst GoIV will think it's a Dragonite because of the learning, and that should be fixed when you correct the Pokemon choice ;-)
