### ISSUE TITLE
Alolan Diglett has wrong stats

### ISSUE THREAD

**Issue by lramati** [farkam135/GoIV#954]
This issue was discussed in depth in the discord, but the tldr is as follows:
I caught a lv24 CP 303 hp 21 alolan Diglett that in-game appriasal told me was a wonder, with all stats being impressive. GoIV told me that no IV combination matched the stats and appraisal.
After some digging udnp discovered that alolan Diglett had it's attack stat mistakenly set to 108 instead of the correct 109

As an aside, it's worth mentioning that multiple online IV checkers also seem to have incorrect stats for alolan Diglett at time of writing

Furthermore, I don't know how feasible it is, but assuming some sort of testing infrastructure already exists, would it be possible to have a test that downloaded the most up to date game master file and made sure all of GoIV's values matched?

**Comment by udnp** [comment]
@lramati Thanks for your report.
Could you check the latest version GoIV?
Already this issue should have been fixed.

**Comment by lramati** [comment]
Works great! Thanks

**Comment by wuzhuoqing** [comment]
@udnp looks I am still seeing similar issue.

GOIV V5.2.2

Just hatched Alolan Diglett 
lvl 20, CP 253, HP 19, 
Team Mysic Wonder, Best is Defense, Impressive.

GOIV give 14/13/13 or 13/15/13 and 0 possible combination after appraisal.
https://pokemon.gameinfo.io/en/tools/iv-calculator gives 13/14/13 which looks

**Comment by wuzhuoqing** [comment]
Thanks for update. You are right, it is not recognized as alolan on my phone (Samsung s9+). Sorry I missed this part. Once I manually select Alola it gives correct IV values.

**Comment by udnp** [comment]
@wuzhuoqing If you ok about this issue, could you close this?

**Comment by wuzhuoqing** [comment]
@udnp I am not the one opened the issue so seems I cannot close it. @lramati could you please help to close it?

**Comment by udnp** [comment]
@wuzhuoqing I'm sorry for my mistake... Thanks for your support.
@lramati If you ok about this issue, could you close this?

**Comment by nahojjjen** [comment]
I'll close it as a repository moderator ^^
